---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Updates Package Cache CentOS
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Updates Package Cache Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: all
  become: true
  roles:
    - jenkins-server
