ansible_port: 22
apache_package_name: apache2
apache_service: apache2
php_package_name: php
ssh_users: "sysadmin ansible"
ssh_template_file: sshd_config_ubuntu.j2
fail2ban_package: fail2ban
fail2ban_template_file: jail-conf_ubuntu.j2
fail2ban_distro_path: paths-debian.conf
ban_time: 30m
max_retry: 3
