- name: Create user sysadmin
  tags: always
  user:
    name: sysadmin
    state: present
    shell: /bin/bash
    createhome: yes

- name: Add sudoer file for sysadmin
  tags: always
  copy:
    src: sudoer_sysadmin
    dest: /etc/sudoers.d/sysadmin
    owner: root
    group: root
    mode: 0440

- name: Add SSH key for sysadmin
  tags: always
  authorized_key:
    user: sysadmin
    key: "Public Key"

- name: Generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh

