- name: Create user sysadmin
  tags: always
  user:
    name: sysadmin
    state: present
    shell: /bin/bash
    createhome: yes

- name: Add sudoer file for sysadmin
  tags: always
  copy:
    src: sudoer_sysadmin
    dest: /etc/sudoers.d/sysadmin
    owner: root
    group: root
    mode: 0440

- name: Add SSH key for sysadmin
  tags: always
  authorized_key:
    user: sysadmin
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCggeMZo/9Cen78b+HzbCLLuxe/h1WpMD740nlWvfKkRscCM+heVPJic3D8I/b4Sn1N0/fkEoZmigWUZuBsivL+5po/vOyQiPayCny8o1kRjbGR9BEuHlJH1zuoOAymxPdYmKsatKLKcKGDtNZSBhiwlD9yqEFY9AenjWANFUlLyHOYAAk28S5vnoPQRecy4mgheDMrOb2UKFQowOkBJ2kK6Wy96rcPP1YqWm6b0BgDG6C/THRQudXlH8sAiCGYfL3EB9ETQvxbfy8ilYNRxf9kgWdPuYcZHuLse2RqWKAClIIfXegOmtvCux2Nn0e08Lk8syirxukMdyxislu2CTk+8QYi8/NAjOJYJah1ZR3LIKS0SYvF2eO2wGphYQvZV1lGnPMI8U0rIFRZylY3kXjjW9I4i9B8rpPLgofduhs3VMwNepANg0D0RvXx7YaIxSznI1aaPDwqGcm1X90clWCxVQwdhhEVBiXPW6V40rkvXPsJpSH3Eb31b8XUUy9s4bs= omer@master"

- name: Generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_ssh

